name: Keep App Awake

on:
  schedule:
    - cron: '* * * * *'  # This means: Run every 1 minute

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
    - name: Send request to keep the app awake
      run: |
        curl -I https://mycbseguide-image-processor.onrender.com/
